apiVersion: v1
kind: Service
metadata:
  name: py-gitops-app
  namespace: py-gitops-app
spec:
  type: NodePort
  selector:
    app: py-gitops-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
